read -p "- Enter page name: " name

path="pages/$name"
pathTest="__tests__/$name"
namePage=$(sed '
       h;
       y/QUVWXZDERMATOGLYPHICSBFJKN/quvwxzdermatoglyphicsbfjkn/;
       G;
       s/\(.\)[^\n]*\n.\(.*\)/\1\2/;
     ' <<<$name)

mkdir -p $path

# ------------------------------------------------------------- #
# Page
# ------------------------------------------------------------- #

echo "import type { NextPage } from 'next';
import Head from 'next/head';

const $namePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>      

      <main>
        $name page
      </main>
    </div>
  );
};

export default $namePage;" > "$path/index.tsx"

# ------------------------------------------------------------- #
# Page test
# ------------------------------------------------------------- #

echo "import { render, screen } from '@testing-library/react';
import $namePage from '@/pages/$name/$namePage';

describe('Tests $name page', () => {
  test('renders page correctly', () => {
    render(<$namePage />);

    expect(screen.getByText('$name Page')).toBeInTheDocument();
	});
});" > "$pathTest/index.test.tsx"

echo "- Page created successfully in $path"
